name: mpfr core forking for GitHub Actions

on:
  push:
    branches:
      - 4.2.1

permissions:
  contents: write
  pull-requests: write

jobs:
  download-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Obtain source code from ftp.gnu.org
        run: |
          wget https://ftp.gnu.org/gnu/mpfr/mpfr-4.2.1.tar.xz -O mpfr-4.2.1.tar.xz

      - name: Install Zstandard for Extraction
        run: sudo apt install -y xz-utils tar

      - name: Extract Source Code into Root Directory
        run: tar --strip-components=1 -xf mpfr-4.2.1.tar.xz

      - name: Commit Changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          rm mpfr-4.2.1.tar.xz
          git add .
          git commit -m "mpfr core forking for GitHub Actions, version 4.2.1"
          git push
